### PR TITLE
add kotlin multiaddr  implementation

### PR DESCRIPTION
**Pull request by changjiashuai**
add kotlin multiaddr  implementation

### CODE REVIEW

**Comment by Stebalien** [comment]
(that points to the multihash implementation :smile:)

**Comment by changjiashuai** [comment]
sorry, I have updated it.

**Comment by changjiashuai** [comment]
@Stebalien bug has fixed please review code.

**Comment by Stebalien** [comment]
Unfortunately, I really don't have time to do a decent review (I've tried to find time but it has obviously been months). However, I'm just going to go ahead and merge this PR as there aren't any other kotlin implementations at the moment anyways.

**Pull request merged**
