### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by RichardLitt**
I filled out the README a bit. This involves moving the protocols into the README, adding some sections - contribute, license, specification - adding badges, making some small syntax changes, and adding three protocols from the js-multiaddr library.

Relevant to #13.

### CODE REVIEW

**Comment by JesseWeinstein** [comment]
FWIW, this LGTM.

**Comment by diasdavid** [comment]
@RichardLitt thank you :) Requires rebase, could you apply it?

**Comment by RichardLitt** [comment]
@diasdavid Done. Can you review again? :)

**Comment by diasdavid** [comment]
👌🏽

**Comment by RichardLitt** [comment]
Thanks!

**Pull request merged**
